const stateNumbers = [
  { state: "Alabama", number: "01" },
  { state: "Alaska", number: "02" },
  { state: "Arizona", number: "04" },
  { state: "Arkansas", number: "05" },
  { state: "California", number: "06" },
  { state: "Colorado", number: "08" },
  { state: "Connecticut", number: "09" },
  { state: "Delaware", number: "10" },
  { state: "Florida", number: "12" },
  { state: "Georgia", number: "13" },
  { state: "Hawaii", number: "15" },
  { state: "Idaho", number: "16" },
  { state: "Illinois", number: "17" },
  { state: "Indiana", number: "18" },
  { state: "Iowa", number: "19" },
  { state: "Kansas", number: "20" },
  { state: "Kentucky", number: "21" },
  { state: "Louisiana", number: "22" },
  { state: "Maine", number: "23" },
  { state: "Maryland", number: "24" },
  { state: "Massachusetts", number: "25" },
  { state: "Michigan", number: "26" },
  { state: "Minnesota", number: "27" },
  { state: "Mississippi", number: "28" },
  { state: "Missouri", number: "29" },
  { state: "Montana", number: "30" },
  { state: "Nebraska", number: "31" },
  { state: "Nevada", number: "32" },
  { state: "New Hampshire", number: "33" },
  { state: "New Jersey", number: "34" },
  { state: "New Mexico", number: "35" },
  { state: "New York", number: "36" },
  { state: "North Carolina", number: "37" },
  { state: "North Dakota", number: "38" },
  { state: "Ohio", number: "39" },
  { state: "Oklahoma", number: "40" },
  { state: "Oregon", number: "41" },
  { state: "Pennsylvania", number: "42" },
  { state: "Rhode Island", number: "44" },
  { state: "South Carolina", number: "45" },
  { state: "South Dakota", number: "46" },
  { state: "Tennessee", number: "47" },
  { state: "Texas", number: "48" },
  { state: "Utah", number: "49" },
  { state: "Vermont", number: "50" },
  { state: "Virginia", number: "51" },
  { state: "Washington", number: "53" },
  { state: "West Virginia", number: "54" },
  { state: "Wisconsin", number: "55" },
  { state: "Wyoming", number: "56" }
];
export default stateNumbers;
